import RPi.GPIO as GPIO
from time import sleep
GPIO.setmode(GPIO.BCM)
GPIO.setup(26,GPIO.OUT)
GPIO.setup(19,GPIO.OUT)
GPIO.setup(13,GPIO.OUT)
GPIO.setup(6,GPIO.OUT)
GPIO.setup(12,GPIO.OUT)
GPIO.setup(16,GPIO.OUT)
GPIO.setup(20,GPIO.OUT)
GPIO.setup(21,GPIO.OUT)
#GPIO.setup(16, GPIO.IN, pull_up_down=GPIO.PUD_UP)
try:
    while True:
        GPIO.output(26, True)
        sleep(0.5)
        GPIO.output(26, False)
        sleep(0.5)
        GPIO.output(19, True)
        sleep(0.5)
        GPIO.output(19, False)
        sleep(0.5)
        GPIO.output(13, True)
        sleep(0.5)
        GPIO.output(13, False)
        sleep(0.5)
        GPIO.output(6, True)
        sleep(0.5)
        GPIO.output(6, False)
        sleep(0.5)
        GPIO.output(12, True)
        sleep(0.5)
        GPIO.output(12, False)
        sleep(0.5)
        GPIO.output(16, True)
        sleep(0.5)
        GPIO.output(16, False)
        sleep(0.5)
        GPIO.output(20, True)
        sleep(0.5)
        GPIO.output(20, False)
        sleep(0.5)
        GPIO.output(21, True)
        sleep(0.5)
        GPIO.output(21, False)
        sleep(0.5)
finally:
    GPIO.cleanup()
